# Generated by Django 2.1.7 on 2019-03-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title_text', models.CharField(max_length=80)),
                ('curse_text', models.CharField(max_length=600)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_id1', models.IntegerField(default=0)),
                ('votes_id2', models.IntegerField(default=0)),
                ('curse_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curse_id1', to='curses.Curse')),
                ('curse_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curse_id2', to='curses.Curse')),
            ],
        ),
    ]
