# Generated by Django 2.1.7 on 2019-03-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='curse_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curse1', to='curses.Curse'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='curse_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curse2', to='curses.Curse'),
        ),
    ]
