# Generated by Django 2.1.7 on 2019-03-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_auto_20190323_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterecord',
            old_name='curse_id1',
            new_name='curse1',
        ),
        migrations.RenameField(
            model_name='voterecord',
            old_name='curse_id2',
            new_name='curse2',
        ),
    ]
